language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
# - 'pypy'    # commented out due to issue #12
install:
  - 'pip install -r requirements/devel.txt --use-mirrors --quiet'
services:
  - mongodb
script: py.test --cov=monk
notifications:
  email:
    - neithere+travis@gmail.com
