language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.5
# - 'pypy'    # commented out due to issue #12
sudo: false
install:
  - pip install -r requirements/devel.txt --use-mirrors --quiet
  - pip install coveralls
services:
  - mongodb
script:
  py.test --cov=monk
after_success:
  coveralls
notifications:
  email:
    - neithere+travis@gmail.com
